name: Django-CI
run-name: ${{ github.actor }} - ${{ github.sha }}


on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.8

jobs:
  django-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Check Comlexity
        run: |
          cd ../
          flake8 . --statistics --max-complexity=10 --exit-zero

      - name: Django-Test and Test
        run: |
          coverage run --source="." manage.py test
          coverage report -m

      - name: Upload Code As Artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: src/**/*.py
